name: Build and Deploy
on:
  push:
    paths:
      - "src/stories/**"
      - "src/components/**"
      - "**.css"
jobs:
  build-storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: false == ( ( github.event_name == 'pull_request' && ( github.event.action == 'closed' || github.event.pull_request.draft == true || contains( github.head_ref, 'dependabot/' ) ) ) || github.event.pull_request.head.repo.fork )
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: npm install
        run: |
          npm ci
      - name: Build Storybook
        run: |
          npm run build:storybook
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: storybook-files
          path: dist

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: storybook-files
          path: dist
      - name: Set branch environment variables
        id: branch-target
        if: github.event_name != 'pull_request'
        run: echo "dir=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Set PR environment variables
        id: pr-target
        if: github.event_name == 'pull_request'
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: echo "dir=pull/${PULL_REQUEST_NUMBER}" >> $GITHUB_OUTPUT
      - name: Commit updates
        run: |
          mkdir -p storybook/${TARGET_DIR}
          rm -rf storybook/${TARGET_DIR}
          mv dist storybook/${TARGET_DIR}
          git add .
          git status
          git diff --staged --quiet && echo 'No changes to commit; exiting!' && exit 0
          git pull --no-edit --quiet
          git commit -m "Deploy storybook for ${TARGET_DIR}."
          git push origin gh-pages
        env:
          TARGET_DIR: ${{ steps.branch-target.outputs.dir }}${{ steps.pr-target.outputs.dir }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
